apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: security-recognize
  name: crowded-storages-security-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storages-local-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: crowded-storages-security-local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  storageClassName: storages-local-sc
  local:
    path: /data/crowded-security-ps/images
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - face-recognize-node1