version: '2.3'
services:
  face_vp:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python3 /app/app.py"
    environment:
      INPUT_STREAM_URL: "rtsp://admin:123456@192.168.1.230:7070/stream1"
      INPUT_STREAM_ID: "1a368699-810d-43cc-96c1-3be5e853a83f"
      OMP_NUM_THREADS: 1
      FILE_STORAGE_PATH_IMAGES: "/app/data/images"
      FILE_STORAGE_PATH_MODELS: "/app/data/models"
      RABBITMQ_BROKER_URL: "amqp://guest:guest@192.168.101.240:5672/"
      CELERY_BROKER_URL: "redis://face-vp-redis:6379"
      STREAM_REDIS: "redis://face-vp-redis:6379/2"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - /data/face/vp_images:/app/data/images
      - /data/face/models/camera_model:/app/data/models
    image: docker-registry.vnpttiengiang.vn/face/face_vp:1.0
    runtime: nvidia
    depends_on:
      - face-vp-redis
  server_stream_facevp:
    command: "python3 /app/server_streaming.py"
    environment:
      RABBITMQ_BROKER_URL: "amqp://guest:guest@192.168.101.240:5672/"
      STREAM_REDIS: "redis://face-vp-redis:6379/2"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    image: docker-registry.vnpttiengiang.vn/face/face_vp:1.0
    ports:
      - 9001:9001
    depends_on:
      - face-vp-redis    
  celery_face_vp:
    command: "celery -A run_celery worker --loglevel=INFO --concurrency=4"
    environment:
      DISTANCE_UNKNOWN: 1.10
      FILE_STORAGE_PATH_IMAGES: "/app/data/images"
      FILE_STORAGE_PATH_MODELS: "/app/data/models"
      RABBITMQ_BROKER_URL: "amqp://guest:guest@192.168.101.240:5672/"
      CELERY_BROKER_URL: "redis://face-vp-redis:6379"
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - /data/face/vp_images:/app/data/images
      - /data/face/models/camera_model:/app/data/models
    image: docker-registry.vnpttiengiang.vn/face/face_vp:1.0
    runtime: nvidia
    depends_on:
      - face-vp-redis
  face-vp-redis:
    image: bitnami/redis:latest
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    container_name: face-vp-redis
  # rabbitmq:
  #   image: rabbitmq:3-management
  #   environment:
  #     RABBITMQ_DEFAULT_USER: guest
  #     RABBITMQ_DEFAULT_PASS: guest
  #   container_name: rabbitmq
  #   ports:
  #     - 15672:15672
  #     - 5672:5672
